# set -g default-command "login-shell"
# tmux display things in 256 colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g history-limit 20000

# automatically renumber tmux windows
set -g renumber-windows on

# unbind default prefix and set it to Ctrl+a
unbind C-b
set -g prefix C-q
bind C-q send-prefix

# for nested tmux sessions
#bind-key a send-prefix

# Activity Monitoring
setw -g monitor-activity off
set -g visual-activity off

# Rather than constraining window size to the maximum size of any client
# connected to the *session*, constrain window size to the maximum size of any
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# make delay shorter
set -sg escape-time 0

# tile all windows
unbind =
bind = select-layout tiled

# cycle through panes
# unbind C-a
# unbind o # this is the default key for cycling panes
# bind ^A select-pane -t:.+

# make window/pane index start with 1
set -g base-index 1
setw -g pane-base-index 1

set-option -g set-titles on
set-option -g set-titles-string "#T - #W"
# set-window-option -g automatic-rename on

######################
#### Key Bindings ####
######################

# quickly open a new window
bind N new-window

# split window and fix path for tmux 1.9
bind-key C-v split-window -h -c "#{pane_current_path}"
bind-key C-s split-window -v -c "#{pane_current_path}"
bind-key _ split-window -v -p 25 -c "#{pane_current_path}" # Makes a horizontal 'testing' pane
bind-key / split-window -h -p 33 -c "#{pane_current_path}" # Makes a vertical 'testing' pane

# synchronize all panes in a window
bind y setw synchronize-panes

# pane movement shortcuts
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

bind-key -r C-n select-window -t :+
bind-key -r C-p select-window -t :-

# Resize pane shortcuts
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

#set -g @resurrect-save 'S'
#set -g @resurrect-restore 'R'

# maximizing and restoring windows
unbind Up
bind Up new-window -d -n fullscreen \; swap-pane -s fullscreen.1 \; select-window -t fullscreen
unbind Down
bind Down last-window \; swap-pane -s fullscreen.1 \; kill-window -t fullscreen

# set vi mode for copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
# more settings to make copy-mode more vim-like
#unbind [
#bind Escape copy-mode
#unbind p
#bind p paste-buffer
#bind -t vi-copy 'v' begin-selection
#bind -t vi-copy 'y' copy-selection


# Make pbcopy and pbpaste work
# See https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
#set-option -g default-command "reattach-to-user-namespace -l zsh"

# Buffers to/from Mac clipboard, yay tmux book from pragprog
#bind C-c run "tmux save-buffer - | reattach-to-user-namespace pbcopy"
#bind C-v run "tmux set-buffer $(reattach-to-user-namespace pbpaste); tmux paste-buffer"
#set-option -g default-command "/bin/bash -c 'which reattach-to-user-namespace >/dev/null && exec reattach-to-user-namespace $SHELL -l || exec $SHELL -l'"

# Copy and paste from and to tmux
#bind C-c run "tmux save-buffer - | reattach-to-user-namespace pbcopy"
# bind C-v run "reattach-to-user-namespace pbpaste | tmux load-buffer - && tmux paste-buffer"
#set-option -g default-command "/bin/bash -c 'which reattach-to-user-namespace >/dev/null && exec reattach-to-user-namespace $SHELL -l || exec $SHELL -l'"

# reload config file
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

##############################
### Color & Style Settings ###
##############################

set-option -sa terminal-overrides ",xterm*:Tc"

source ~/.config/tmux/theme.sh
